name: Telink TL721X build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-20.04
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.15.2
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west blobs fetch hal_telink
        west blobs list hal_telink -f '{status} {path}' | grep '^M lib_zephyr_tl721x.a$' && exit 1
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build TL721X basic/blinky
      run: |
        cd ..
        west build -b tl7218x                  -d build_blinky_tl721x                    zephyr/samples/basic/blinky                          -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721x samples/basic/button
      run: |
        cd ..
        west build -b tl7218x     -d build_button_tl721x                      zephyr/samples/basic/button                          -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X basic/blinky_pwm
      run: |
        cd ..
        west build -b tl7218x                  -d build_blinky_pwm_tl721x                zephyr/samples/basic/blinky_pwm                          -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X hello_world
      run: |
        cd ..
        west build -b tl7218x                  -d build_hello_tl721x                     zephyr/samples/hello_world                               -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X drivers/watchdog
      run: |
        cd ..
        west build -b tl7218x                  -d build_watchdog_tl721x                  zephyr/samples/drivers/watchdog                          -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    # - name: Build TL721X sensor/sht3xd
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_sht3xd_tl721x                    zephyr/samples/sensor/sht3xd                             -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    # - name: Build TL721X bluetooth/peripheral_ht
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_peripheral_ht_tl721x             zephyr/samples/bluetooth/peripheral_ht                   -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    # - name: Build TL721X net/openthread/cli
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_ot_cli_tl721x                    zephyr/samples/net/openthread/cli                        -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DOVERLAY_CONFIG=overlay-telink-fixed-mac.conf

    # - name: Build TL721X net/openthread/coprocessor in RCP configuration with UART interface
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_ot_coprocessor_rcp_uart_tl721x   zephyr/samples/net/openthread/coprocessor                -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DOVERLAY_CONFIG=overlay-rcp.conf

    # - name: Build TL721X net/sockets/echo_server for OpenThread
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_ot_echo_server_tl721x            zephyr/samples/net/sockets/echo_server                   -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DOVERLAY_CONFIG=overlay-ot.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    # - name: Build TL721X net/sockets/echo_client for OpenThread
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_ot_echo_client_tl721x            zephyr/samples/net/sockets/echo_client                   -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    # - name: Build TL721X subsys/usb/console for USB driver
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_usb_console_tl721x              zephyr/samples/subsys/usb/console                        -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    # - name: Build TL721X crypto/mbedtls
    #   run: |
    #     cd ..
    #     west build -b tl7218x                  -d build_crypto_mbedtls_tl721x           zephyr/tests/crypto/mbedtls                              -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DCONFIG_MBEDTLS_ECP_C=y -DCONFIG_MBEDTLS_ECP_ALL_ENABLED=y

    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_tl721x/zephyr/zephyr.bin                    telink_build_artifacts/tl721x_blinky.bin
        cp ../build_blinky_pwm_tl721x/zephyr/zephyr.bin                telink_build_artifacts/tl721x_blinky_pwm.bin
        cp ../build_hello_tl721x/zephyr/zephyr.bin                     telink_build_artifacts/tl721x_hello.bin
        cp ../build_button_tl721x/zephyr/zephyr.bin                     telink_build_artifacts/tl721x_button.bin
        cp ../build_watchdog_tl721x/zephyr/zephyr.bin                  telink_build_artifacts/tl721x_watchdog.bin
        cp ../modules/hal/telink/zephyr/blobs/lib_zephyr_tl721x.a      telink_build_artifacts/lib_zephyr_tl721x.a

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          telink_build_artifacts/*
